baseURL = 'https://econologicien.com/'
languageCode = "fr"
title = "Éconologicien"
theme = 'ananke'

[params]
  background_color_class = "bg-near-black"
  featured_image = ""
  description = "L'art de l'optimisation systémique des ressources individuelles (temps, argent, énergie)."
  # Ajout de liens pour le header
  site_social_links = [
      {name = "GitHub", url = "https://github.com/Maalshekto/econologicien"},
  ]

# SEO et structure
[taxonomies]
  tag = "tags"
  category = "categories"

# Configuration pour le sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
